modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
showAsResourcePack=false

[[mods]]
modId="memeenv"
version="${file.jarVersion}"
displayName="Meme Environment"
authors="lqlovehehe"
description="""
梗明星环境 - 提供排行榜、换梗、菜单、全局效果、摔落伤害取消等游戏环境组件
"""
